var genButton = $("#gen");
var textarea = $("#source");
var docs = $("#docs");
textarea.val("");
var documentContent;
var cssText;
function generateDocuments() {
    docs.children().remove();
    docs.append("<p>Parsing...</p>");
    setTimeout(function () {
        var sourceCode = textarea.val();
        var result = DTSDoc.program.parse(new Source(sourceCode, 0));
        docs.append("<p>Parsing finished</p><p>Document generating...</p>");
        var global = result.value;
        var members = global.members;
        documentContent = $('<div/>');
        documentContent.append($('<h2>Contents</h2>'));
        documentContent.append($('<ul class="contents"><li><a href="#members">Members</a></li><li><a href="#hierarchy">Class Hierarchy</a></li></ul>'));
        documentContent.append('<a name="members" />');
        documentContent.append('<h2>Members</h2>');
        documentContent.append(members.map(function (m) {
            return m.toHTML();
        }));
        documentContent.append($('<hr/>'));
        documentContent.append('<a name="hierarchy" />');
        documentContent.append('<h2>Class Hierarchy</h2>');
        documentContent.append(global.toHierarchyHTML());
        documentContent.append($('<hr/>'));
        documentContent.append($('<footer>Generated by <a href="https://github.com/kontan/dtsdoc">DTSDoc</a></footer>'));
        docs.children().remove();
        docs.append(documentContent);
        var source = encodeURIComponent(documentContent.html());
        source = "<body>" + source;
        source = '<html><head><meta charset="utf-8"><style>' + cssText + '</style></head>' + source + "</html>";
        $('#downloadLink').attr('href', "data:text/html," + source);
    }, 1);
}
genButton.click(function () {
    generateDocuments();
});
$.ajax("style.css", {
    contentType: "text/plain",
    dataType: "text",
    success: function (data) {
        cssText = data;
    }
});
var sample = "../three.d.ts/three.d.ts";
$.ajax(sample, {
    contentType: "text/plain",
    dataType: "text",
    success: function (data) {
        textarea.val(data);
        generateDocuments();
    }
});
function generateHierarchy(global) {
    var section = $('<section/>');
    return section;
}
